import ConfigHandler from '@/components/ConfigHandler'
import ConfigNavbar from '@/components/ConfigNavbar'


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function ConfigLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='pt-10 '>
        <ConfigNavbar />
        {children}
        <ConfigHandler />
    </div>
  )
}
