import { ConfigHandler } from "@/components/ConfigHandler";
import ConfigNavbar from "@/components/ConfigNavbar";
import { UserAccountNav } from "@/components/UserAccountNav";
import { ComboboxDemo } from "@/components/ui/combobox";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-[svh] pt-5">
      <div className="w-full flex justify-between">
        <ComboboxDemo />
        <UserAccountNav user={{name: "Xavi"}} />
      </div>
      {children}
    </div>
  );
}
