import { ConfigHandler } from "@/components/ConfigHandler";
import ConfigNavbar from "@/components/ConfigNavbar";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function ConfigLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="pt-5">
      <ConfigNavbar />
      {children}
      <div className="fixed bottom-2 left-0 right-0 max-w-md m-auto">
        <ConfigHandler />
      </div>
    </div>
  );
}
